# Generated by Django 2.1.2 on 2018-10-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181024_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='_student_friend_+', to='student.Student'),
        ),
    ]
